### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by ThreepE0** [gddc/xsi#1]
I was wondering if you could provide some examples for use;  I'd love to contribute, but I'm having a hard time getting off the ground with this class.  

Trying EventsChannel() after entering the xsp host, auth info, etc... and getting the following error:

File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by gddc** [comment]
I'm happy to try to help, but the issue you're currently up against isn't related to anything in the EventsChannel itself.  The traceback is indicating that it can't locate the host you're trying to connect to, or you're encountering some other DNS lookup issue. I'd suggest double-checking the value you set in `baseurl` on ~ line 37 in the EventsChannel.  You might try using the IP Address of your XSI Server there as well.  If you can get it connected the general idea is that the Channel will subscribe to events and put the XML Responses into `self.processed`.  I normally set up a consumer thread on whatever will utilize the channel to do something like this (assumes `channel` is an EventsChannel instance):

```
def consumer(self):
    while True:
        if not channel.processed:
            sleep(1)
        event = channel.processed.popleft()
        # handling here for the contents of the XML Response.
```

**Comment by ThreepE0** [comment]
Great!  I had 'http://' before my address, and that was jamming things up.  Now that I'm connected, I'm not really sure how to subscribe, or use the methods.  This is most likely me being new to Python, and nothing else.  Would you mind pointing me in the right direction?

I know I'm connected because I see something like:

<?xml version="1.0" ?><Channel xmlns="http://schema.broadsoft.com/xsi"><channelSetId>3081050c-5e15-11e4-a6cd-6c4008997a8e</channelSetId>

I tried the following:

#myChannel = EventsChannel()
#myChannel.getuserdnd(myChannel, '5555555555')
#TypeError: unbound method getuserdnd() must be called with EventsChannel instance as first argument (got type instance instead)

This is most certainly my education level, not an issue with your code.  I'd really appreciate a nudge in the right direction though.

**Comment by gddc** [comment]
No problem.  The calls to `getuserdnd` are instance methods - the placeholder `self` parameter is implied - you don't pass it directly.  Also, you want to pass in a SIP, which doesn't usually correspond directly to a phone number (though it can).  So your call signature should look something like `myChannel.getuserdnd('<sipvalue@host>')`.  You'll need to work with your provider to find out what their sip values are - mine typically took the form company.extension@voip.provider.net.

**Comment by ThreepE0** [comment]
Thanks again!  I really appreciate it.  I could have sworn I tried just that, but then again it works, so I must be mistaken.

I tried:
reply = myChannel.getuserdnd('mySipUsername@domain.com')
I got: `<overrides.http.MyResponse instance at 0x109352f80>`

running help(reply) helped me figure out that I should be able to run 'reply.read(),' which worked, returning with:
{"DoNotDisturb":{"@xmlns":{"$":"http:\/\/schema.broadsoft.com\/xsi"},"active":{"$":"false"},"ringSplash":{"$":"false"}}}

I know my biggest barrier in getting this working was being new to Python.  I was searching for answers, reading articles about Python, etc... but I wasn't getting anywhere.  I really appreciate your help.

**Comment by ThreepE0** [comment]
Hi, 

Sorry to bother you again, but I was hoping to get up to speed on getting xsi-events working with this class for live-streaming.  If I run my script on the python command line, I can see events coming in for the user subscription.  How would I access and consume this data in a script? 

I tried the consumer example you had posted, but I got 'IndexError: pop from an empty deque'
I tried checking to see if channel.processed wasn't empty, but it just constantly returned as empty.

**Comment by gddc** [comment]
Aaron,

I'll try to help, but I haven't spent much time with this code lately - we
moved away from the phone provider who was using BroadSoft as a backend, so
we're not longer employing the XSI interface.

What call signature are you using to create your EventsChannel?  It only
starts up its processor daemon thread if you're requesting a conduit
(though that's set to True by default).  Do you have anything in the
channel.data deque?  Can you send over a sample of the XML it is printing
to your console?

Thanks,
--Dan

**Comment by ThreepE0** [comment]
``` python
from EventsChannel import EventsChannel
import time
from time import sleep
channel = EventsChannel()
reply = channel.usersubscribe('ABC123@mysip.com');


while True:
    print channel.data
    print channel.processed
```

If I run the above as a script, I get something like 'deque([])' repeatedly.

If I run the same at the python command prompt excluding the 'while True' loop, I get the expected xis events.  Here's an example:

```
2015-05-15 14:47:01.025338 ('<?xml version="1.0" encoding="UTF-8"?>\n<xsi:Event xsi1:type="xsi:SubscriptionEvent" xmlns:xsi="http://schema.broadsoft.com/xsi" xmlns:xsi1="http://www.w3.org/2001/XMLSchema-instance"><xsi:eventID>9ca79035-63e1-435e-acd4-710c9ba1f5fd</xsi:eventID><xsi:sequenceNumber>2</xsi:sequenceNumber><xsi:userId>admin@mysip.com</xsi:userId><xsi:externalApplicationId>c2aea1f5-fb32-11e4-a313-6c4008997a8e</xsi:externalApplicationId><xsi:subscriptionId>a9980865-40cd-4e45-8d47-76552fd4e265</xsi:subscriptionId><xsi:channelId>a5b02667-a21a-4741-8c7a-ec1d3906ae22</xsi:channelId><xsi:targetId>ABC123@mysip.com</xsi:targetId><xsi:eventData xsi1:type="xsi:CallOriginatedEvent"><xsi:call><xsi:callId>callhalf-10434103911:0</xsi:callId><xsi:extTrackingId>15238216:1</xsi:extTrackingId><xsi:personality>Originator</xsi:personality><xsi:state>Alerting</xsi:state><xsi:remoteParty><xsi:address>tel:18004444444</xsi:address><xsi:callType>Network</xsi:callType></xsi:remoteParty><xsi:endpoint xsi1:type="xsi:AccessEndpoint"><xsi:addressOfRecord>ABC123@mysip.com</xsi:addressOfRecord></xsi:endpoint><xsi:appearance>1</xsi:appearance><xsi:startTime>1431715602513</xsi:startTime></xsi:call></xsi:eventData></xsi:Event>',)
```

**Comment by gddc** [comment]
Gotcha.  Thanks for that.  I believe you're up against the Global
Interpreter Lock in python and it's messing with you from the interactive
shell.  You need to let the main thread sleep so that the background
threads can get something done, then come back to the main thread to
process things.  If I recall correctly, from the interactive shell you'd do
something like this:

while not channel.processed:
  sleep(1)

That way the main processing thread will give over control to the
background threads until they have a chance to populate that deque, then it
should return to the interactive prompt where you can consume the events
via channel.processed.popleft().  In most of my implementations I have a
Main() somewhere that does something like:

while not shutdown_condition:
  sleep(1)

So I'm already pretty much just idle except for whatever the EventChannel
triggers.

I think that should help, but if not let me know.

--Dan

**Comment by ThreepE0** [comment]
Thanks for the reply.  The interactive shell is the one that's showing the subscription events correctly.  Even if I close that window altogether, I don't get any output if I run the script as 'python myscript.py' 

I tried creating a main function that sleeps, but it just causes the terminal to hang, I'm assuming because the script is sleeping indefinitely.

**Comment by gddc** [comment]
That's really quite odd, to be entirely honest.  That it's outputting the xml you're receiving seems to indicate that it's making it into the body of the handlexml method.  From there, there's a check about heartbeats that your XML passes, a test for ChannelTerminated events, which it also passes, then a try / catch that should push it into the processed deque.

I'm ... not sure I have a ton more to go on at present.  You haven't made any changes to the w3 or schema definitions at the start of the EventsChannel have you?  Can you attach with a debugger and see if the handlexml method is being entered into on your system?

**Comment by ThreepE0** [comment]
I think I figured it out, but I could use a pointer in fixing it if you don't mind.  The reason I'm getting output via interactive shell, is that EventsChannel is using 'debug' to spit the output out.  Is there any way to define a file for output, or print to the main out instead?

Sorry, I'm very new to Python, so I'm sure I sound like a complete idiot.  Your help is much appreciated

**Comment by ThreepE0** [comment]
strike that;  Changed the debug function name, still works on interactive mode but not run as script

**Comment by gddc** [comment]
Debug is just a wrapper function for print that timestamps the output - it's defined at the top of the file.

I am having a hard time understanding why you never get the XML blocks pushed into channel.processed.  As long as the schema and w3 values at the top of the module are still correct, and using the XML sample you posted, this works:

```
>>> xml.tag == '{%s}Event' % schema
True
```

This check passes (or skips, however you want to think about it):

```
>>> xml.attrib['{%s}type' % w3] == 'xsi:ChannelTerminatedEvent'
False
```

And this produces the expected exception:

```
>>> xml[6].attrib['{%s}type' % w3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '{http://www.w3.org/2001/XMLSchema-instance}type'
```

Which should put you in the except block that appends the XML to the processed deque.  The Channel is keeping a look out for closed channels or terminated subscriptions (the server I was connected to was unreliable at best).  If what it received wasn't either of those things, it should put the XML into processed so a consumer can deal with it.  You could ... move the call to `self.processed.append(xml)` on line 225 up to directly after line 194 where xml gets parsed and see what effect, if any, that had.
